name: Publish to npm

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
          package-manager-cache: false # https://docs.npmjs.com/trusted-publishers#step-2-configure-your-cicd-workflow

      - run: npm ci
      - run: npm run build
      - run: npm test -- run

      - name: Publish
        run: npm publish
